---
ID: "82438c4f-99c1-457d-b191-d27b19f3cd35"
Parent: "d29fdf95-ab73-4752-ba1a-0b4e81bc8b2d"
Template: "d29fdf95-ab73-4752-ba1a-0b4e81bc8b2d"
Path: /sitecore/templates/Feature/Sitecore Scriban Extensions/Scriban Include Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {D29FDF95-AB73-4752-BA1A-0B4E81BC8B2D}
    {CB401771-43AB-4F1E-B711-8C5EA7C37BE1}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210213T122815Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "024dfc71-85e8-4a31-9690-cc5f4b08ffdc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210213T122853Z
